#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

// 初始化应用
$app = new Application();

// 注册命令
$app->add(new \MyShell\Commands\ViewCommands());
$app->add(new \MyShell\Commands\ProgressBarCommand());
$app->add(new \MyShell\Commands\OutPutCommand());
$app->add(new \MyShell\Commands\TableCommand());
$app->add(new \MyShell\Commands\EnvCommand());
$app->add(new \MyShell\Commands\InputCommand());
$app->add(new \MyShell\Commands\QuestionCommand());
$app->add(new \MyShell\Commands\TestCommand());
$app->add(new \MyShell\Commands\IoCommand());

// 运行
$app->run();